[document]
title = "Informe IEEE - Aprendizaje No Supervisado sobre Objetos Celestes SDSS DR17"
author = "Jheison Martinez Bolivar"
template = "ieee"

[build]
entry = "main.tex"
bib = "bib/references.bib"
